services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    #restart: on-failure:3
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/linesmonitor
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      db:
        condition: service_healthy
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: linesmonitor
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3