services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=lines-monitor
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin